"""empty message

Revision ID: 602cd8a0e33a
Revises: e4b268486d4c
Create Date: 2019-07-10 22:50:24.640045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602cd8a0e33a'
down_revision = 'e4b268486d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masterclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_masterclass_timestamp'), 'masterclass', ['timestamp'], unique=False)
    op.add_column('location', sa.Column('masterclass_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'masterclass', ['masterclass_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'masterclass_id')
    op.drop_index(op.f('ix_masterclass_timestamp'), table_name='masterclass')
    op.drop_table('masterclass')
    # ### end Alembic commands ###
