"""empty message

Revision ID: e4b268486d4c
Revises: 333d75324f3d
Create Date: 2019-07-10 22:47:41.788951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b268486d4c'
down_revision = '333d75324f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.Column('street_number', sa.String(length=5), nullable=True),
    sa.Column('street_name', sa.String(length=100), nullable=True),
    sa.Column('town_or_city', sa.String(length=50), nullable=True),
    sa.Column('postcode', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_building'), 'location', ['building'], unique=False)
    op.create_index(op.f('ix_location_postcode'), 'location', ['postcode'], unique=False)
    op.create_index(op.f('ix_location_street_name'), 'location', ['street_name'], unique=False)
    op.create_index(op.f('ix_location_town_or_city'), 'location', ['town_or_city'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_town_or_city'), table_name='location')
    op.drop_index(op.f('ix_location_street_name'), table_name='location')
    op.drop_index(op.f('ix_location_postcode'), table_name='location')
    op.drop_index(op.f('ix_location_building'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
